services:
  apimock:
    image: wiremock/wiremock
    ports:
    - "8090:8080"
    volumes:
    - type: bind
      source: ./apimock
      target: /home/wiremock
    command:
      - -verbose
      - -global-response-templating

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development